### ISSUE TITLE
Docservice: Unable to verify the first certificate

### ISSUE THREAD

**Issue by gabbler97** [ONLYOFFICE/Kubernetes-Docs#96]
I have installed the whole stack as it was advised in the readme. After that, I added a let's encrypt certificate manually to the ingress and turned off the rejectUnauthorized flag by mounting it the default.json file as a ConfigMap. Afterward I set hostAliases to the docservice, converter and the nextcloud deployment so they can resolve the hostname.
Everything was fine and I was able to connect the nextcloud to the documentserver and I created a docx file but as I open it the following error appears in the logs of docservice container:

[2022-01-31T16:06:41.318] [ERROR] nodeJS - sendServerRequest error: docId = 2064873878;url = https://cloud.mydomain.com/apps/onlyoffice/track?doc=eyJ0eXAiOmZpbGVJZCI6MjY5LCJmaWxlUGF0aCI6IlwvRG9jdW1lbnQuZG9jeCIsInNoYXJlVG9rZW4iOm51bGwsImFjdGlvbiI6InRyYWNrIn0.mIAPa0jDYqvzojVaXXtr1IYkUipVaEh-3WbUG7aBGQA;data = {"key":"2064873878","status":2,"url":"https://documentserver.mydomain.com/cache/files/2064873878_1811/output.docx/output.docx?md5=PsPlPZyEMDGqxrkV6PBIwA&expires=1643646102&filename=output.docx","history":{},"users":["ocjsd52tu6j7_admin"],"actions":[{"type":0,"userid":"ocjsd_admin"}],"lastsave":"2022-01-31T15:35:08.000Z","notmodified":false,"filetype":"docx"}
Error: unable to verify the first certificate
    at TLSSocket.onConnectSecure (_tls_wrap.js:1514:34)
    at TLSSocket.emit (events.js:400:28)
    at TLSSocket._finishInit (_tls_wrap.js:936:8)
    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:708:12)

**Comment by gabbler97** [comment]
Solved. When you import the certificate to Kubernetes use the privkey.pem and fullchain.pem and DO not use the cert.pem. If you use cert.pem the docserver will not able to verify the certificate and that results the error above.
